imp - Migrated to LocaleStation (files)
---

We have migrated the localization files to LocaleStation in an attempt to
execute our migration plan, which is set to start next week.

We have only placed the JSON files, which means that the language code is
not changed to adapt to the new system. Hence, such code will fail to read
the new files we've added.

Unfortunately, this means that Nitrocid KS will no longer start until we
adapt the language code. It will crash instantly on startup with the below
error message:

----------------------------------------------

System.TypeInitializationException: The type initializer for
'Nitrocid.Languages.LanguageManager' threw an exception.
 ---> Nitrocid.Kernel.Exceptions.KernelException: There is an error in the
kernel, one of the kernel addons, one of your mods, or one of the kernel
components. If the routine tried to process your input, ensure that you've
written all the parameters correctly.

--- Exception info ---
- Error type: Reflection [95]
  Error message: There was an error in the reflection system.

--- Additional info ---
- The module that caused the fault provided this additional information
that may help you further
  Resource Metadata.json not found for type Languages in Nitrocid,
Version=0.2.0.0, Culture=neutral, PublicKeyToken=21c82ea14d2d7748

----------------------------------------------

Please note that we've done this before the API migration, which will
happen later. We'll make the localization files stay in the entry point of
the kernel until the migration is complete. They'll be found in the Core
part.

---

Type: imp
Breaking: False
Doc Required: False
Backport Required: False
Part: 1/1